# Generated by Django 5.1.7 on 2025-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
