# Generated by Django 5.1.7 on 2025-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_message_receiver_name_message_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
    ]
