# Generated by Django 5.1.7 on 2025-03-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_remove_message_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
